os: linux
dist: xenial
language: python
python:
- '3.7'
- '3.6'
install:
- sudo apt-get install python-enchant
- pip install -r requirements-test.txt
- pip install .
script:
- make test
- make build
after_success:
- codecov
deploy:
  - provider: pypi
    username:
      secure: <pypi_username>
    password:
      secure: <pypi_password>
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = 3.6
  - provider: releases
    overwrite: true
    token:
      secure: <github_token>
    file_glob: true
    file: dist/*
    on:
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = 3.6
